In [102]:
# 1. На улице встретились N друзей. Каждый пожал руку всем остальным друзьям (по одному разу). Сколько рукопожатий было?
# Примечание. Решите задачу при помощи построения графа.
# ----------------------------------------------------------------------------------------------------------------------------

N = int(input('Количество друзей: '))

# ПЕРВЫЙ ВАРИАНТ: заполнение пустого графа 
        
if N < 2:
    print('Нет достаточного количества рук.')

graph = []

for i in range(N):
    for j in range(N):
        if i != j:
            graph.append((i, j))

print(*graph, sep='\n')
print(f'Счетчик рукопожатий: {int(len(graph) / 2)}\n')


# ВТОРОЙ ВАРИАНТ: более громоздкий
# каждый human должен пожать руку всем кроме себя, т.е. строки выглядят как [0, 1(1), ... , 1(N)] и т.д [i, i] == 0

# можно создать соответствующую матрицу
import numpy as np

graph2 = np.ones((N, N))
for i in range (0, len(graph2)):
    for j in range (0, len(graph2)):
        if j == i:
            graph2[i][j] = 0

print(graph2)

# а потом посчитать руки
hands = 0      
for i in range (0, len(graph2)):
    for j in range (0, len(graph2)):
        if graph2[i][j] == 1:
            hands += 1
           
print(f'Счетчик рукопожатий: {int(hands / 2)}')

Количество друзей: 7
(0, 1)
(0, 2)
(0, 3)
(0, 4)
(0, 5)
(0, 6)
(1, 0)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(1, 6)
(2, 0)
(2, 1)
(2, 3)
(2, 4)
(2, 5)
(2, 6)
(3, 0)
(3, 1)
(3, 2)
(3, 4)
(3, 5)
(3, 6)
(4, 0)
(4, 1)
(4, 2)
(4, 3)
(4, 5)
(4, 6)
(5, 0)
(5, 1)
(5, 2)
(5, 3)
(5, 4)
(5, 6)
(6, 0)
(6, 1)
(6, 2)
(6, 3)
(6, 4)
(6, 5)
Счетчик рукопожатий: 21

[[0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0.]]
Счетчик рукопожатий: 21
